# Generated by Django 3.0.4 on 2020-05-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imgurl',
            field=models.TextField(),
        ),
    ]
